### ISSUE TITLE
Devconsole error from autofill.js

### ISSUE THREAD

**Issue by Harrietlol** [duckduckgo/duckduckgo-autofill#219]
Hey there, While i was using the dev console to debug my website i looked in the console and saw an error from the duckduckgo extension, I am using Chromium on Ubuntu 22 LTS 

Here are the details of the error:

```
autofill.js:10733 Uncaught TypeError: Cannot read properties of undefined (reading 'encrypt')
    at Object.45 (autofill.js:10733:33)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at Object.44../captureDdgGlobals.js (autofill.js:10579:49)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at Object.54.../../../packages/device-api/index.js (autofill.js:11616:25)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at Object.56../android.transport.js (autofill.js:11714:23)
 ```

**Comment by GioSensation** [comment]
Hello @Harrietlol . Are you testing your site on an insecure context? The browser won't make certain APIs available in insecure context. For example, if you're using a local dev server like http://something.mylocal, the browser will likely treat that as an insecure context. If you use localhost, instead, the browser will treat it as secure. You can read more here: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts.

If the problem is different please ping me again so we can investigate further. Thank you!

**Comment by Harrietlol** [comment]
Oh, It might be because of http but would it be possible to catch the error in a try loop or something?

**Comment by GioSensation** [comment]
This will be fixed in https://github.com/duckduckgo/duckduckgo-autofill/pull/225. Thanks for reporting!

**Comment by Harrietlol** [comment]
Closing this issue as complete :+1:
